DROP TRIGGER IF EXISTS releases_ai;
DROP TRIGGER IF EXISTS artists_ai;
DROP TRIGGER IF EXISTS releases_au;
DROP TRIGGER IF EXISTS artists_au;
DROP TRIGGER IF EXISTS releases_ad;
DROP TRIGGER IF EXISTS artists_ad;
DROP TABLE IF EXISTS releases_fts;